import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Search, Shield, Brain, FileText, Gavel, AlertTriangle, 
  ChevronRight, Eye, Download, MessageSquare, Send, Bot,
  TrendingUp, TrendingDown, Clock, DollarSign, CheckCircle2,
  XCircle, Scale, Camera, Ruler, File, X
} from "lucide-react";

/* ═══════════════════════════════════════════
   TYPES
═══════════════════════════════════════════ */
type FaultType = "supplier" | "client";
type ClaimPhase = "inspection" | "atlas" | "cv-analysis" | "claim" | "penalties";

interface LifecycleClaim {
  id: string;
  title: string;
  equipment: string;
  tag: string;
  fault: FaultType;
  status: string;
  claimAmount: number;
  penaltyPerDay: number;
  delayDays: number;
  totalLD: number;
  supplier: string;
  contract: string;
  severity: "critical" | "major";
  findings: string[];
  evidence: { name: string; type: string; date: string }[];
  aiClaimText: string;
}

/* ═══════════════════════════════════════════
   DATA
═══════════════════════════════════════════ */
const lifecycleClaims: LifecycleClaim[] = [
  {
    id: "LC-001",
    title: "Weld Integrity Failure — Longitudinal Seam",
    equipment: "Deethanizer Condenser",
    tag: "G1-22E05",
    fault: "supplier",
    status: "Claim Submitted",
    claimAmount: 892000,
    penaltyPerDay: 22000,
    delayDays: 70,
    totalLD: 1540000,
    supplier: "Volga Heavy Machinery JSC",
    contract: "FIDIC Cl. 11.1 · Contract §8.3",
    severity: "critical",
    findings: [
      "Surface crack 40mm in HAZ — zero tolerance per GOST §5.2",
      "Linear indication on RT film — confirmed by Level III",
      "Excessive reinforcement 4.2mm (max 3mm)",
      "Incomplete WPS/PQR documentation",
    ],
    evidence: [
      { name: "VT-Report-E05-LS-001.pdf", type: "report", date: "2024-10-15" },
      { name: "MPI-Film-HAZ-Zone-A.jpg", type: "photo", date: "2024-10-15" },
      { name: "RT-Film-LS-001-Scan.dcm", type: "scan", date: "2024-10-16" },
      { name: "NCR-2024-0312.pdf", type: "document", date: "2024-10-17" },
      { name: "Weld-Measurement-Report.pdf", type: "measurement", date: "2024-10-15" },
    ],
    aiClaimText: `FORMAL CLAIM NOTICE — CLM-2024-001

To: Volga Heavy Machinery JSC — Quality Assurance Department
From: RCA Project Management — LNG Mega-Project Phase II
Date: 2024-10-25
Reference: PO-LNG-2024-0847 · NCR-2024-0312

Subject: Claim for Defective Workmanship — Deethanizer Condenser G1-22E05

Dear Sir/Madam,

We hereby notify you of a formal claim under FIDIC Red Book Clause 11.1 (Defects Liability) and Purchase Order Terms & Conditions §8.3 for defective workmanship identified during Third-Party Inspection of the above-referenced equipment.

DEFECT SUMMARY:
1. Surface crack extending 40mm into Heat Affected Zone (HAZ) at longitudinal seam weld toe
2. Radiographic examination confirms linear indication — incomplete fusion at root (42mm length)
3. Weld reinforcement measured at 4.2mm, exceeding maximum allowable 3.0mm per GOST-34347 §5.2
4. Undercut depth 0.8mm exceeds 0.5mm specification limit
5. Incomplete WPS/PQR documentation package (3 of 7 documents missing)

FINANCIAL IMPACT:
- Direct repair and re-inspection costs: $892,000
- Liquidated Damages: 70 days × $22,000/day = $1,540,000
- Total claim value: $2,432,000

LEGAL BASIS:
Per FIDIC Red Book Cl. 11.1, the Contractor is liable for all costs arising from defects attributable to workmanship. Evidence chain established through 14 documented inspection records with photographic, radiographic, and measurement evidence.

REQUIRED ACTION:
Supplier must accept this claim within 14 calendar days and provide a remediation plan. Failure to respond will result in escalation per Contract §12.1 (Dispute Resolution).

This claim is supported by AI-verified evidence chain with full traceability.

Regards,
RCA Claims Management System
Generated by Atlas AI — Claim Module v3.2`,
  },
  {
    id: "LC-002",
    title: "Coating System Failure — Surface Prep Below Grade",
    equipment: "Amine Circulation Pump Casing",
    tag: "P1-31P01",
    fault: "supplier",
    status: "Open — Penalty Active",
    claimAmount: 345000,
    penaltyPerDay: 15000,
    delayDays: 44,
    totalLD: 660000,
    supplier: "KazPipe Industries LLP",
    contract: "Contract §6.2 · ISO 12944",
    severity: "major",
    findings: [
      "Surface preparation Sa 2.0 instead of required Sa 2.5",
      "DFT primer 62μm — below 60μm lower tolerance",
      "3 pinholes/m² detected by holiday test",
    ],
    evidence: [
      { name: "Blast-Profile-Comparison.pdf", type: "report", date: "2024-11-05" },
      { name: "DFT-Readings-Report.xlsx", type: "measurement", date: "2024-11-05" },
      { name: "Holiday-Test-Map.pdf", type: "scan", date: "2024-11-06" },
      { name: "NCR-2024-0398.pdf", type: "document", date: "2024-11-07" },
    ],
    aiClaimText: `FORMAL CLAIM NOTICE — CLM-2024-002

To: KazPipe Industries LLP — Quality Department
From: RCA Project Management — LNG Mega-Project Phase II
Date: 2024-11-10
Reference: PO-LNG-2024-1203 · NCR-2024-0398

Subject: Coating Non-Conformance — Amine Circulation Pump P1-31P01

DEFECT SUMMARY:
1. Surface preparation achieved Sa 2.0 — specification requires Sa 2.5 per ISO 8501-1
2. DFT primer readings averaging 62μm — below minimum 60μm tolerance band
3. Holiday detection test reveals 3 pinholes per m² — exceeds zero-pinhole specification

FINANCIAL IMPACT:
- Full re-blast and re-coat costs: $345,000
- Liquidated Damages: 44 days × $15,000/day = $660,000
- Total claim value: $1,005,000

Supplier must accept within 14 calendar days.

Regards,
RCA Claims Management System`,
  },
  {
    id: "LC-003",
    title: "Late Specification Handover — Client Fault",
    equipment: "All Cryogenic Piping — Area 300",
    tag: "AREA-300",
    fault: "client",
    status: "EOT Granted",
    claimAmount: 0,
    penaltyPerDay: 40000,
    delayDays: 70,
    totalLD: 2800000,
    supplier: "N/A — Client Engineering",
    contract: "FIDIC Cl. 1.9 · Cl. 8.4",
    severity: "critical",
    findings: [
      "Specification 77 days late vs contractual deadline",
      "70 days fabricator idle time — documented daily",
      "Material procurement could not start without approved spec",
      "Contractor entitled to EOT per FIDIC Cl. 8.4",
    ],
    evidence: [
      { name: "Contract-Schedule-Baseline.pdf", type: "document", date: "2024-03-15" },
      { name: "Reminder-Letters-Bundle.pdf", type: "document", date: "2024-05-10" },
      { name: "Daily-Idle-Time-Log.xlsx", type: "measurement", date: "2024-05-31" },
      { name: "EOT-Claim-Submission.pdf", type: "document", date: "2024-06-05" },
    ],
    aiClaimText: `EXTENSION OF TIME CLAIM — CLIENT FAULT

To: Client Engineering Department
From: EPC Contractor — Claims Department
Date: 2024-06-05
Reference: FIDIC Cl. 20.1 · ENG-LNG-2024-CRYO

Subject: EOT Claim — Late Cryogenic Piping Specification (77 Days)

This claim is filed under FIDIC Cl. 8.4 (Extension of Time) due to CLIENT-caused delay.

The cryogenic piping specification was due 15-Mar-2024. Actual receipt: 31-May-2024 (77 days late).

IMPACT:
- 70 days fabricator idle time (45 men/day)
- Prolongation costs: $2,800,000
- Contractor is entitled to full cost recovery

This is a CLIENT FAULT case. No penalties apply to contractor.

Regards,
RCA Claims Management System`,
  },
  {
    id: "LC-004",
    title: "Vibration Exceeds API Limit — Compressor",
    equipment: "Propane Compressor",
    tag: "G1-51K01",
    fault: "supplier",
    status: "On Hold — Vendor Review",
    claimAmount: 185000,
    penaltyPerDay: 18000,
    delayDays: 45,
    totalLD: 810000,
    supplier: "Shenyang Blower Works",
    contract: "API 617 · Contract §9.1",
    severity: "critical",
    findings: [
      "Vibration 4.5 mm/s exceeds API 617 limit (3.5 mm/s)",
      "Coupling misalignment suspected",
      "Baseplate grouting voids detected",
    ],
    evidence: [
      { name: "Vibration-Analysis-Report.pdf", type: "report", date: "2026-02-22" },
      { name: "Alignment-Laser-Readings.xlsx", type: "measurement", date: "2026-02-22" },
      { name: "Baseplate-Borescope-Video.mp4", type: "video", date: "2026-02-23" },
    ],
    aiClaimText: `FORMAL CLAIM NOTICE — LC-004

To: Shenyang Blower Works — Engineering Department
Subject: API 617 Non-Conformance — Propane Compressor G1-51K01

Vibration levels at 4.5 mm/s exceed the API 617 maximum of 3.5 mm/s.
Coupling misalignment and baseplate grouting voids are suspected root causes.

FINANCIAL IMPACT:
- Repair & specialist mobilization: $185,000
- Liquidated Damages: 45 days × $18,000/day = $810,000
- Total: $995,000

Supplier must respond within 14 days.

Regards, RCA Claims Management System`,
  },
];

const phases: { key: ClaimPhase; label: string; icon: typeof Search }[] = [
  { key: "inspection", label: "AI Inspection", icon: Search },
  { key: "atlas", label: "Atlas AI", icon: Brain },
  { key: "cv-analysis", label: "CV Analysis", icon: Eye },
  { key: "claim", label: "Claim Generation", icon: FileText },
  { key: "penalties", label: "Penalties & LD", icon: Gavel },
];

const kpiData = {
  supplier: {
    totalClaims: 3,
    totalValue: 3005000,
    avgDelay: 53,
    activePenalties: 2,
    recoveredAmount: 892000,
    pendingAmount: 2113000,
  },
  client: {
    totalClaims: 1,
    totalValue: 2800000,
    avgDelay: 70,
    activePenalties: 0,
    eotGranted: 1,
    prolongationCost: 2800000,
  },
};

/* ═══════════════════════════════════════════
   AI CLAIM BOT (simulated typing)
═══════════════════════════════════════════ */
const useTypingEffect = (text: string, speed = 8, active = false) => {
  const [displayed, setDisplayed] = useState("");
  const indexRef = useRef(0);

  useEffect(() => {
    if (!active) { setDisplayed(""); indexRef.current = 0; return; }
    const interval = setInterval(() => {
      if (indexRef.current < text.length) {
        setDisplayed(text.slice(0, indexRef.current + 1));
        indexRef.current++;
      } else {
        clearInterval(interval);
      }
    }, speed);
    return () => clearInterval(interval);
  }, [text, speed, active]);

  return displayed;
};

/* ═══════════════════════════════════════════
   COMPONENT
═══════════════════════════════════════════ */
const LNGFullLifecycleDemo = () => {
  const [activePhase, setActivePhase] = useState<ClaimPhase>("inspection");
  const [selectedClaim, setSelectedClaim] = useState<LifecycleClaim>(lifecycleClaims[0]);
  const [faultFilter, setFaultFilter] = useState<"all" | FaultType>("all");
  const [detailTab, setDetailTab] = useState<"overview" | "evidence" | "claim-bot">("overview");
  const [botActive, setBotActive] = useState(false);
  const botText = useTypingEffect(selectedClaim.aiClaimText, 6, botActive);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [botText]);

  useEffect(() => {
    setBotActive(false);
  }, [selectedClaim]);

  const filteredClaims = lifecycleClaims.filter(
    c => faultFilter === "all" || c.fault === faultFilter
  );

  const formatCurrency = (n: number) => 
    new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);

  const evidenceIcon = (type: string) => {
    switch (type) {
      case "report": return <FileText className="w-3.5 h-3.5" />;
      case "photo": return <Camera className="w-3.5 h-3.5" />;
      case "measurement": return <Ruler className="w-3.5 h-3.5" />;
      case "scan": return <Eye className="w-3.5 h-3.5" />;
      case "video": return <Eye className="w-3.5 h-3.5" />;
      default: return <File className="w-3.5 h-3.5" />;
    }
  };

  return (
    <div className="space-y-12">

      {/* ── LIFECYCLE FLOW ── */}
      <div className="relative">
        <div className="flex items-center justify-between gap-0 overflow-x-auto">
          {phases.map((p, i) => {
            const Icon = p.icon;
            const isActive = activePhase === p.key;
            return (
              <button
                key={p.key}
                onClick={() => setActivePhase(p.key)}
                className={`flex-1 min-w-[140px] relative group transition-all duration-300 ${
                  isActive ? "" : "opacity-50 hover:opacity-80"
                }`}
              >
                <div className={`flex flex-col items-center gap-2 py-4 px-3 border-b-2 transition-all ${
                  isActive ? "border-primary" : "border-foreground/10"
                }`}>
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center transition-all ${
                    isActive ? "bg-primary text-white" : "bg-foreground/5 text-foreground/40"
                  }`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <span className={`text-[10px] font-bold uppercase tracking-wider ${
                    isActive ? "text-primary" : "text-foreground/40"
                  }`}>{p.label}</span>
                </div>
                {i < phases.length - 1 && (
                  <ChevronRight className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 w-4 h-4 text-foreground/20 z-10" />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* ── KPI CARDS — Supplier vs Client ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Supplier Fault KPIs */}
        <div className={`border-2 p-6 transition-all cursor-pointer ${
          faultFilter === "supplier" ? "border-[#AE3D3D] bg-[#AE3D3D]/[0.02]" : "border-foreground/10 hover:border-foreground/20"
        }`} onClick={() => setFaultFilter(faultFilter === "supplier" ? "all" : "supplier")}>
          <div className="flex items-center gap-3 mb-4">
            <div className="w-3 h-3 bg-[#AE3D3D]" />
            <span className="text-xs font-bold uppercase tracking-wider text-foreground">Supplier Fault</span>
            <AlertTriangle className="w-4 h-4 text-[#AE3D3D] ml-auto" />
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <div className="text-2xl font-bold text-foreground">{kpiData.supplier.totalClaims}</div>
              <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Active Claims</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-[#AE3D3D]">{formatCurrency(kpiData.supplier.totalValue)}</div>
              <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Total Value</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-foreground">{kpiData.supplier.avgDelay}d</div>
              <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Avg Delay</div>
            </div>
          </div>
          <div className="flex items-center gap-4 mt-4 pt-4 border-t border-foreground/5">
            <div className="flex items-center gap-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-[#6EA996]" />
              <span className="text-[10px] text-foreground/50">Recovered: <span className="font-bold text-[#6EA996]">{formatCurrency(kpiData.supplier.recoveredAmount)}</span></span>
            </div>
            <div className="flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5 text-[#F5A623]" />
              <span className="text-[10px] text-foreground/50">Pending: <span className="font-bold text-[#F5A623]">{formatCurrency(kpiData.supplier.pendingAmount)}</span></span>
            </div>
          </div>
        </div>

        {/* Client Fault KPIs */}
        <div className={`border-2 p-6 transition-all cursor-pointer ${
          faultFilter === "client" ? "border-[#F5A623] bg-[#F5A623]/[0.02]" : "border-foreground/10 hover:border-foreground/20"
        }`} onClick={() => setFaultFilter(faultFilter === "client" ? "all" : "client")}>
          <div className="flex items-center gap-3 mb-4">
            <div className="w-3 h-3 bg-[#F5A623]" />
            <span className="text-xs font-bold uppercase tracking-wider text-foreground">Client Fault</span>
            <Scale className="w-4 h-4 text-[#F5A623] ml-auto" />
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <div className="text-2xl font-bold text-foreground">{kpiData.client.totalClaims}</div>
              <div className="text-[9px] text-foreground/40 uppercase tracking-wider">EOT Claims</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-[#F5A623]">{formatCurrency(kpiData.client.totalValue)}</div>
              <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Prolongation</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-foreground">{kpiData.client.avgDelay}d</div>
              <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Avg Delay</div>
            </div>
          </div>
          <div className="flex items-center gap-4 mt-4 pt-4 border-t border-foreground/5">
            <div className="flex items-center gap-1.5">
              <Shield className="w-3.5 h-3.5 text-[#F5A623]" />
              <span className="text-[10px] text-foreground/50">EOT Granted: <span className="font-bold text-foreground">{kpiData.client.eotGranted}</span></span>
            </div>
            <div className="flex items-center gap-1.5">
              <DollarSign className="w-3.5 h-3.5 text-[#F5A623]" />
              <span className="text-[10px] text-foreground/50">Cost Recovery: <span className="font-bold text-[#F5A623]">{formatCurrency(kpiData.client.prolongationCost)}</span></span>
            </div>
          </div>
        </div>
      </div>

      {/* ── CLAIM CARDS + DETAIL PANEL ── */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-0 border border-foreground/10">
        
        {/* LEFT: Claim List */}
        <div className="lg:col-span-4 border-r border-foreground/10">
          <div className="px-4 py-3 border-b border-foreground/10 bg-foreground/[0.02]">
            <span className="text-[10px] font-bold uppercase tracking-wider text-foreground/50">
              {faultFilter === "all" ? "All Claims" : faultFilter === "supplier" ? "Supplier Fault Claims" : "Client Fault Claims"} ({filteredClaims.length})
            </span>
          </div>
          <div className="divide-y divide-foreground/5">
            {filteredClaims.map(claim => (
              <button
                key={claim.id}
                onClick={() => { setSelectedClaim(claim); setDetailTab("overview"); setBotActive(false); }}
                className={`w-full text-left px-4 py-4 transition-all hover:bg-foreground/[0.02] ${
                  selectedClaim.id === claim.id ? "bg-foreground/[0.04] border-l-2 border-primary" : "border-l-2 border-transparent"
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[10px] font-mono text-foreground/30">{claim.id}</span>
                  <div className="flex items-center gap-1.5">
                    <div className={`w-2 h-2 rounded-full ${claim.fault === "supplier" ? "bg-[#AE3D3D]" : "bg-[#F5A623]"}`} />
                    <span className={`text-[9px] font-bold uppercase ${claim.fault === "supplier" ? "text-[#AE3D3D]" : "text-[#F5A623]"}`}>
                      {claim.fault}
                    </span>
                  </div>
                </div>
                <h4 className="text-sm font-bold text-foreground leading-tight mb-1">{claim.equipment}</h4>
                <p className="text-[10px] text-foreground/40">{claim.tag} · {claim.supplier}</p>
                <div className="flex items-center justify-between mt-2">
                  <span className="text-xs font-bold text-[#AE3D3D]">{formatCurrency(claim.claimAmount + claim.totalLD)}</span>
                  <span className="text-[9px] text-foreground/30">{claim.delayDays}d delay</span>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* RIGHT: Detail Panel */}
        <div className="lg:col-span-8 flex flex-col min-h-[600px]">
          {/* Tabs */}
          <div className="flex border-b border-foreground/10">
            {(["overview", "evidence", "claim-bot"] as const).map(tab => (
              <button
                key={tab}
                onClick={() => {
                  setDetailTab(tab);
                  if (tab === "claim-bot") setBotActive(true);
                }}
                className={`flex-1 py-3 text-[10px] font-bold uppercase tracking-wider transition-all border-b-2 ${
                  detailTab === tab ? "border-primary text-primary bg-primary/[0.02]" : "border-transparent text-foreground/40 hover:text-foreground/60"
                }`}
              >
                {tab === "claim-bot" ? (
                  <span className="flex items-center justify-center gap-1.5">
                    <Bot className="w-3.5 h-3.5" /> AI Claim Writer
                  </span>
                ) : tab === "evidence" ? (
                  <span className="flex items-center justify-center gap-1.5">
                    <Camera className="w-3.5 h-3.5" /> Evidence ({selectedClaim.evidence.length})
                  </span>
                ) : (
                  <span className="flex items-center justify-center gap-1.5">
                    <Eye className="w-3.5 h-3.5" /> Claim Overview
                  </span>
                )}
              </button>
            ))}
          </div>

          {/* Tab Content */}
          <div className="flex-1 overflow-auto">
            <AnimatePresence mode="wait">
              {/* OVERVIEW TAB */}
              {detailTab === "overview" && (
                <motion.div key="overview" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-6 space-y-6">
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <div className={`px-2 py-0.5 text-[9px] font-bold uppercase rounded ${
                        selectedClaim.fault === "supplier" ? "bg-[#AE3D3D]/10 text-[#AE3D3D]" : "bg-[#F5A623]/10 text-[#F5A623]"
                      }`}>
                        {selectedClaim.fault === "supplier" ? "Supplier Fault" : "Client Fault"}
                      </div>
                      <span className={`px-2 py-0.5 text-[9px] font-bold uppercase rounded ${
                        selectedClaim.severity === "critical" ? "bg-[#AE3D3D]/10 text-[#AE3D3D]" : "bg-[#F5A623]/10 text-[#F5A623]"
                      }`}>{selectedClaim.severity}</span>
                    </div>
                    <h3 className="text-xl font-bold text-foreground">{selectedClaim.title}</h3>
                    <p className="text-sm text-foreground/40 mt-1">{selectedClaim.equipment} · {selectedClaim.tag}</p>
                  </div>

                  {/* KPI Row */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="border border-foreground/10 p-3">
                      <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Claim Amount</div>
                      <div className="text-lg font-bold text-foreground">{formatCurrency(selectedClaim.claimAmount)}</div>
                    </div>
                    <div className="border border-foreground/10 p-3">
                      <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Liquidated Damages</div>
                      <div className="text-lg font-bold text-[#AE3D3D]">{formatCurrency(selectedClaim.totalLD)}</div>
                    </div>
                    <div className="border border-foreground/10 p-3">
                      <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Penalty / Day</div>
                      <div className="text-lg font-bold text-foreground">{formatCurrency(selectedClaim.penaltyPerDay)}</div>
                    </div>
                    <div className="border border-foreground/10 p-3">
                      <div className="text-[9px] text-foreground/40 uppercase tracking-wider">Delay Days</div>
                      <div className="text-lg font-bold text-foreground">{selectedClaim.delayDays}</div>
                    </div>
                  </div>

                  {/* Details */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <div className="text-[10px] font-bold uppercase tracking-wider text-foreground/40 mb-2">Supplier</div>
                      <p className="text-sm text-foreground">{selectedClaim.supplier}</p>
                    </div>
                    <div>
                      <div className="text-[10px] font-bold uppercase tracking-wider text-foreground/40 mb-2">Contract Basis</div>
                      <p className="text-sm text-foreground font-mono">{selectedClaim.contract}</p>
                    </div>
                  </div>

                  {/* Findings */}
                  <div>
                    <div className="text-[10px] font-bold uppercase tracking-wider text-foreground/40 mb-3">Findings</div>
                    <div className="space-y-2">
                      {selectedClaim.findings.map((f, i) => (
                        <div key={i} className="flex items-start gap-2">
                          <XCircle className="w-3.5 h-3.5 text-[#AE3D3D] mt-0.5 flex-shrink-0" />
                          <span className="text-sm text-foreground/70">{f}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="text-[10px] font-mono text-foreground/20 pt-4 border-t border-foreground/5">
                    Status: {selectedClaim.status} · Total Exposure: {formatCurrency(selectedClaim.claimAmount + selectedClaim.totalLD)}
                  </div>
                </motion.div>
              )}

              {/* EVIDENCE TAB */}
              {detailTab === "evidence" && (
                <motion.div key="evidence" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-6">
                  <div className="text-[10px] font-bold uppercase tracking-wider text-foreground/40 mb-4">
                    Evidence Files — {selectedClaim.evidence.length} documents
                  </div>
                  <div className="space-y-2">
                    {selectedClaim.evidence.map((ev, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.05 }}
                        className="flex items-center gap-3 p-3 border border-foreground/5 hover:border-foreground/15 transition-all group"
                      >
                        <div className="w-8 h-8 bg-foreground/5 flex items-center justify-center text-foreground/40 group-hover:text-primary transition-colors">
                          {evidenceIcon(ev.type)}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="text-sm font-medium text-foreground truncate">{ev.name}</div>
                          <div className="text-[10px] text-foreground/30">{ev.date} · {ev.type}</div>
                        </div>
                        <Download className="w-4 h-4 text-foreground/20 group-hover:text-primary transition-colors" />
                      </motion.div>
                    ))}
                  </div>
                </motion.div>
              )}

              {/* AI CLAIM BOT TAB */}
              {detailTab === "claim-bot" && (
                <motion.div key="claim-bot" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex flex-col h-full">
                  {/* Bot Header */}
                  <div className="px-6 py-3 bg-foreground/[0.02] border-b border-foreground/5 flex items-center gap-3">
                    <div className="w-7 h-7 bg-primary rounded-full flex items-center justify-center">
                      <Bot className="w-4 h-4 text-white" />
                    </div>
                    <div>
                      <div className="text-xs font-bold text-foreground">Atlas AI — Claim Writer</div>
                      <div className="text-[9px] text-foreground/40">Generating formal claim with full evidence chain…</div>
                    </div>
                    <div className="ml-auto flex items-center gap-1.5">
                      <div className="w-2 h-2 bg-[#6EA996] rounded-full animate-pulse" />
                      <span className="text-[9px] text-[#6EA996] font-bold">LIVE</span>
                    </div>
                  </div>

                  {/* Bot Messages */}
                  <div ref={scrollRef} className="flex-1 overflow-auto p-6 min-h-[400px]">
                    {/* System message */}
                    <div className="flex gap-3 mb-6">
                      <div className="w-6 h-6 bg-foreground/10 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                        <Bot className="w-3.5 h-3.5 text-foreground/40" />
                      </div>
                      <div className="flex-1">
                        <div className="text-[9px] text-foreground/30 mb-1">ATLAS AI · CLAIM MODULE</div>
                        <div className="bg-foreground/[0.03] border border-foreground/5 rounded-lg p-4">
                          <pre className="text-xs text-foreground/70 whitespace-pre-wrap font-mono leading-relaxed">
                            {botText}
                            {botText.length < selectedClaim.aiClaimText.length && (
                              <span className="inline-block w-1.5 h-4 bg-primary animate-pulse ml-0.5" />
                            )}
                          </pre>
                        </div>
                        {botText.length >= selectedClaim.aiClaimText.length && (
                          <motion.div
                            initial={{ opacity: 0, y: 5 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="flex items-center gap-3 mt-3"
                          >
                            <button className="flex items-center gap-1.5 text-[10px] font-bold text-primary border border-primary/20 rounded px-3 py-1.5 hover:bg-primary/5 transition-colors">
                              <Download className="w-3 h-3" /> Download PDF
                            </button>
                            <button className="flex items-center gap-1.5 text-[10px] font-bold text-[#6EA996] border border-[#6EA996]/20 rounded px-3 py-1.5 hover:bg-[#6EA996]/5 transition-colors">
                              <Send className="w-3 h-3" /> Send to Supplier
                            </button>
                          </motion.div>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Input (decorative) */}
                  <div className="px-6 py-3 border-t border-foreground/5 bg-foreground/[0.01]">
                    <div className="flex items-center gap-3 bg-foreground/[0.03] border border-foreground/10 rounded-lg px-4 py-2.5">
                      <MessageSquare className="w-4 h-4 text-foreground/20" />
                      <span className="text-sm text-foreground/30 flex-1">Ask Atlas AI to modify claim details…</span>
                      <Send className="w-4 h-4 text-foreground/20" />
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LNGFullLifecycleDemo;
